### ISSUE TITLE
Logger crashes with zap.Time argument

### ISSUE THREAD

**Issue by niktheblak** [dhduvall/gcloudzap#1]
The logger adapter crashes if logger.Info/Error etc is given a `zap.Time` argument.

```
panic: interface conversion: interface {} is *time.Location, not time.Time

goroutine 1 [running]:
github.com/dhduvall/gcloudzap.clone(0x0, 0xc0000df180, 0x1, 0x1, 0x1)
	/Users/niko/go/pkg/mod/github.com/dhduvall/gcloudzap@v0.1.1/gcloudzap.go:252 +0x1201
github.com/dhduvall/gcloudzap.(*Core).Write(0xc00026af60, 0x0, 0xbf637287b5822e60, 0x44cffa, 0x1a900e0, 0x0, 0x0, 0x1601f74, 0x8, 0x0, ...)
	/Users/niko/go/pkg/mod/github.com/dhduvall/gcloudzap@v0.1.1/gcloudzap.go:174 +0xb9
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0002a80b0, 0xc0000df180, 0x1, 0x1)
```

Minimal working example (set `GOOGLE_APPLICATION_CREDENTIALS` before running):

```go
package main

import (
	"time"

	"github.com/dhduvall/gcloudzap"
	"go.uber.org/zap"
)

func main() {
	logger, err := gcloudzap.NewProduction("test-project", "test-logger")
	if err != nil {
		panic(err)
	}
	logger.Info("Time now", zap.Time("ts", time.Now()))
}
```

**Comment by niktheblak** [comment]
You might want to make a new release from master because I see this issue is already fixed in master.

**Comment by dhduvall** [comment]
Sorry for such a long delay; I've added a `v0.2` tag that points to that version.
